//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace companyweb1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        public int Id { get; set; }

        [Required]
        [RegularExpression("^[A-Z]+[a-z]*$", ErrorMessage = "First letter must be Uppercase followed by Lowercase letters and Only Alphates allowed ")]
        public string Name { get; set; }

        [Required]
        public double Salary { get; set; }

        [Required]
        public string Designation { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString ="{0:MM/dd/yyyy}")]
        [Required(ErrorMessage = "Date must be in format dd/mm/yyyy")] 
        [Display(Name ="Date of Birth ")]
        public System.DateTime DOF { get; set; }

        [Required]
        public string Gender { get; set; }


        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        [Required(ErrorMessage = "Date must be in format dd/mm/yyyy")]
        [Display(Name = "Date of Joining ")]
        public System.DateTime D_O_Joining { get; set; }
    }
}
